spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/diana?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: be
    password: 1112

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 100MB
      max-request-size: 100MB

server:max-http-header-size: 400000
server:
  tomcat:
    max-http-form-post-size: 20MB



jwt.secret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1